### ISSUE TITLE
Example Requested: AzAPI 

### ISSUE THREAD

**Issue by kevball2** [lonegunmanb/newres#281]
Hoping for an example on using newres with AzAPI. Is it capable of pulling down any resource using the resource API version?

**Comment by lonegunmanb** [comment]
Thanks @kevball2 for opening this issue, for now this tool doesn't support generating a specified AzAPI resource, now it only reads the resource schema and generate resource block based on that. But as we might adopt AzAPI as AVM's primary provider, I'm thinking of supporting such feature. If we want to do it we have to write a special generator to generate block based on rest api spec.

I'll discuss with my team, personally I think this feature request makes sense to me and is a high valuable one.

Anyone who would like this feature could leave a thumb up here, more thumbs we got, the sooner I can bring this feature to `newres`.
